url: https://p.myfiles.ga
title: pages | myfiles.ga
description: your pages
theme: jekyll-theme-hacker
timezone: Asia/Calcutta
exclude: []
keep_files: [keep]
include: [include]
permalink: pretty
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
